name: smartstruct_generator
description: smartstruct - A dart bean mapper annotation processor - the easy nullsafe way!
version: 1.3.0
homepage: https://github.com/smotastic/smartstruct
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ">=1.0.1 <2.0.0"
  source_gen_test: ">=1.0.2 <2.0.0"
  test: ">=1.20.1 <2.0.0"
dependencies:
  analyzer: ">=4.0.0 <5.0.0"
  build: ">=2.2.1 <3.0.0"
  code_builder: ">=4.1.0 <5.0.0"
  path: ">=1.8.1 <2.0.0"
  #smartstruct:
  #  path: ../smartstruct
  #smartstruct: ^1.3.0
  smartstruct:
    git:
      url: https://github.com/luissalgadofreire/smartstruct
      ref: develop
      path: smartstruct
  source_gen: ">=1.2.1 <2.0.0"
#dependency_overrides:
#  smartstruct:
#    path: ../smartstruct
